### ISSUE TITLE
Case-insensitive toggle for filters

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#14]
It'd be nice to have a checkbox to make filters case-insensitive to avoid having to create complex duplicate entries to cover all possibilities.

The Youtube channel I told you about before (https://www.youtube.com/feeds/videos.xml?channel_id=UCoxg3Kml41wE3IPq-PC-LQw) is an example of a feed not following a pattern and mixing up cases in different post titles. I could shorten the filter I've created for it to only three keywords if it wasn't case-sensitive:

    [T|t]railer|TRAILER|[I|i]nterview|INTERVIEW|[P|p]lay.?through|PLAY.?THROUGH

**Comment by onli** [comment]
Okay. I do not want to add a checkbox for that, since we already have regex-support (and the filter block is likely to get more complicated in the future anyway). But I understand that a regex-sensitive filter like that gets too complicated. I made a small patch just now that enables `/regex/flag` syntax. You could then use the `i` flag and write it like this:

    /trailer|interview|play.?through/i
