### ISSUE TITLE
"Internal Server Error" when invalid URL is entered in feed block

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#19]
Create a feed block with the URL `https://www.pipes.digital/`, connect it to `Out`, and try to save and view your pipe.

A more specific error message should be displayed on the main interface instead of generating a blank screen with the vague "Internal Server Error".

**Comment by anewuser** [comment]
I'm getting the same error with this: https://www.pipes.digital/feed/DpOrjQOw

What's wrong with it?

**Comment by onli** [comment]
The combine block had a bug where it died when one of the input pipes had no description. This is fixed now.

For your initial concern I added HTML5 from validation, but I observed since then that this does not trigger yet properly if the input box was never focused. I still hope to trigger that validation with some javascript on save.

**Comment by onli** [comment]
I had a new try on this, and I think I eliminated the 500ers we realistically can prevent:

 1. When blocks like the filter block are  given no input, they will just let their input through
 2. When the feedblock fails to download a feed (because the url is invalid, or that there is no feed on the linked page) it will output a minimal rss reef explaining the problem in the description

Thanks for reporting this, this helps a lot making pipes better.
