### ISSUE TITLE
"Public Pipes" show your own pipes as if they belonged to other people

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#23]
I've made my pipes public. I see a "fork" (but not "edit") button below each thumbnail on https://www.pipes.digital/pipes

Have you considered having a single unified page to show both all personal and public pipes? The user's own pipes could be shown at the top  and the public third-party ones below them, or in a separate tab, section or column on the same page. This would solve this problem and that dilemma over hiding or not "My Pipes" in a menu.

**Comment by onli** [comment]
Yes, I did consider it :) It was even my initial design. 

My decision against it was because I wanted a distinct place for the public pipes. So far the two interfaces are not too different. But I imagined that in the future they might differ more, for example with each public pipe getting its own linkable page and comments. I'm not sure that will be the right way to go, but I wanted to have that possibility.

Having both sites living under one URL and in a separate tab could work, but udner this perspective it does not feel better than the current solution to me, where all the private stuff (pipes, settings, logout) is bundled under the avatar image at the top right. But quite possible I'll revisit this later on.

**Comment by onli** [comment]
I pushed an update for this: Your own pipes under /pipes are now marked with a red title bar, and the title bars under "my pipes" are now also red (for consistency). The fork button for those pipes get hidden, but the edit button reappears.

I think that should make it clearer.
