### ISSUE TITLE
Export/backup pipes

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#39]
Have you considered adding an option for accounts with regular and above plans to export/backup their pipes?

**Comment by onli** [comment]
Yes :) The problem is that there is nothing to do with such an export, no way to run them locally for example or to import them somewhere else.

**Comment by anewuser** [comment]
I do hope your service lasts forever, but a backup would be a nice way to keep a copy of the list of all the feeds/URLs and regexes I've used, if for some reason you need to urgently move to San Marino or Singapore and abandon all of your old projects behind.

**Comment by onli** [comment]
You were right about this. I did not want to see it like that at the time, probably because this feature is a bit scary. The only thing I realized as a reason to postpone this was the uselessness of the feature, but maybe my subconsciousness tricked me there. 

Because it just does not matter. Even if it is not possible right now to run the exported data, it is data that belongs to the user. And if someone would really do the work and write a launcher for the data, that would just make Pipes more useful. To anyone wanting to do this, there are script making the Yahoo Pipes json work, I know of https://github.com/ggaughan/pipe2py. It won't translate directly as pipes.digital has different blocks and I'd be very surprised if my json data has the same structure (I by choice opted not to look at that before implementing my site), it might still be a good starting point.

@anewuser In the Settings is now an export button, which will export the raw json a pipe consists of. At the very least you can get all the feeds/URLs and regexes like that. This button is active also for free users. Could you give me feedback whether the function works for you like this?

**Comment by anewuser** [comment]
Thank you! It works. 

The only minor issue is that Firefox thinks it is an HTML Document file while downloading it.

**Comment by onli** [comment]
I added a content type header of application/json. As a list of json lines the file by itself is not valid json, but that should be the best fit.
