### ISSUE TITLE
Background doesn't fill the whole screen

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#48]
This happens to the background when the Firefox window isn't maximized:

![firefox](https://user-images.githubusercontent.com/6733770/52971006-946f2880-3394-11e9-9ba9-84a0ff0b1495.png)

Firefox 65.0.1 
Windows 10

**Comment by onli** [comment]
Sadly not easy to fix.

I have a workaround ready: You can drag the canvas now, which will move the whole area around, which fixes this situation for me. That was disabled for now in Firefox because Firefox was buggy, https://bugzilla.mozilla.org/show_bug.cgi?id=1428091 is the report. But in current versions it works again, the bug seems to have vanished on its own. So I activated it also for Firefox now.

It works for you?

**Comment by anewuser** [comment]
Dragging works, but the blank bar still appears when all sidebar options are expanded:

![pipes](https://user-images.githubusercontent.com/6733770/53108206-649b5e80-3515-11e9-82f1-998082c68008.png)

This isn't a big deal, though, since we can just maximize the window.

**Comment by onli** [comment]
Yeah, I fear that fixing this is not exactly easy and might even be impossible. At least I failed so far to find a working combination of responsive size assignments that makes it 100% high, always. That svg canvas in a html container behaves complicated there.
